### ISSUE TITLE
program closes

### ISSUE THREAD

**Issue by battouusai** [FailSpy/humble-steam-key-redeemer#17]
when i try to redeem or select  options 2 or 3 it closes.

**Comment by FailSpy** [comment]
Hm, sounds like it might be crashing. 

Would you mind running the program from the command line to be able to show any errors?

**Comment by FailSpy** [comment]
Update to the newest version. It will allow you to see a crash message if it occurs before closing.

**Comment by FailSpy** [comment]
Closing for now as there's no further details to work off of. Feel free to re-open if you learn more.
