### ISSUE TITLE
Issue with key filtering and/or retrieval - possibly because gamekey is not unique

### ISSUE THREAD

**Issue by MSDNAndi** [FailSpy/humble-steam-key-redeemer#22]
My already_owned.csv has 130 lines, the redeemed.csv has 970 lines. I renamed and moved the errored.csv to a different folder since I wanted to retry keys that did not work (typically because a dependent key got tried before the main key).
So, 1100 keys should have been filtered?
I got the following output that it filtered 1595 from previous runs.
Where from?
Also it never seems to do anything with the 1 revealed key it did not filter. I also actually have 3 unrevealed keys in my library it seems and one key where the HumbleBundle does not even offer a Reveal button (because the Beta has now ended).

I also see that the line
steam_keys = [key for key in steam_keys if key["gamekey"] not in filtered_keys]
does not actually look for the key things can be redeemed on steam with (redeemed_key_val).
The problem is value of "gamekey" is not unique it seems. I have various games that share that gamekey if they were part of the same bundle.
e.g. Frostpunk was in the February 2020 Humble Choice, so was NIght Call, they have distinct keys to be redeemed on Steam (redeemed_key_val) but share gamekey.

For some reason it does not seem to retry the errored-out codes from earlier runs. For the keys that offer "Reveal your steam key" those keys are currently exceeded btw.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6744335/147981009-da688392-3669-4c47-9c29-2ef9ed6d0aaf.png">

=FailSpy's Humble Bundle Helper!=-
--------------------------------------
Filtered 1595 keys from previous runs
2 Steam keys total -- 1 revealed, 1 unrevealed
Would you like to redeem on Humble as-yet un-revealed Steam keys? (Revealing keys removes your ability to generate gift links for them) [y/n] n
Successfully signed in on Steam.
Getting your owned content to avoid attempting to register keys already owned...
Filtered out game keys that you already own on Steam; 0 keys unowned.
Press ENTER to close terminal

Now if I change the line
to
steam_keys = [key for key in steam_keys if key["redeemed_key_val"] not in filtered_keys]
I get something that makes more sense at least at first glance.

-=FailSpy's Humble Bundle Helper!=-
--------------------------------------
1597 Steam keys total -- 1592 revealed, 5 unrevealed
Would you like to redeem on Humble as-yet un-revealed Steam keys? (Revealing keys removes your ability to generate gift links for them) [y/n] n
Successfully signed in on Steam.
Getting your owned content to avoid attempting to register keys already owned...
Filtered out game keys that you already own on Steam; 114 keys unowned.
Inside skipped.txt is a list of 318 games that we think you already own, but aren't completely sure
Feel free to REMOVE from that list any games that you would like to try anyways, and when done press Enter to confirm.

**Comment by FailSpy** [comment]
Fixed in 1e1a189 based on your suggestion of using the "redeemed_key_val"
