### ISSUE TITLE
Key "None" in already_owned.csv

### ISSUE THREAD

**Issue by MSDNAndi** [FailSpy/humble-steam-key-redeemer#23]
I end up with various entries in already_owned.csv that show "None" for the actual steam key even though there was a steam key. My expectation would have been to see the actual key it could be redeemed with on Steam.

(I removed the first code from the copy/paste)

,Victor Vran,None
,Shadowrun: Hong Kong - Extended Edition,None
,Stronghold Crusader 2,None
,Twilight Struggle,None
,Pandemic: The Board Game,None
,ENSLAVED™: Odyssey to the West™ Premium Edition,None
,GOD EATER 2: Rage Burst,None
,Yoku's Island Express,None

**Comment by FailSpy** [comment]
This possibly is because you already owned the game, yet had an unrevealed version of the key, so the script avoided redeeming the key so you can still gift it.

If I'm wrong about this I'd be curious to hear. For now, closing this issue.
