### ISSUE TITLE
Suggest to loosen the dependency on fuzzywuzzy

### ISSUE THREAD

**Issue by Agnes-U** [FailSpy/humble-steam-key-redeemer#31]
Hi, your project humble-steam-key-redeemer(commit id: 1d1de43e028de1608d32e7b0e77f85a3ae71574c) requires "fuzzywuzzy==0.18.0" in its dependency. After analyzing the source code, we found that the following versions of fuzzywuzzy can also be suitable, i.e., fuzzywuzzy 0.17.0, since all functions that you directly (2 APIs: fuzzywuzzy.fuzz.token_set_ratio, fuzzywuzzy.fuzz.token_sort_ratio) or indirectly (propagate to 17 fuzzywuzzy's internal APIs and 4 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on fuzzywuzzy from "fuzzywuzzy==0.18.0" to "fuzzywuzzy>=0.17.0,<=0.18.0". This will improve the applicability of humble-steam-key-redeemer and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on fuzzywuzzy?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by FailSpy** [comment]
Loosened, thanks. An automatic tool would be great.
