### ISSUE TITLE
Fatal error when redeeming keys

### ISSUE THREAD

**Issue by metafarion** [FailSpy/humble-steam-key-redeemer#35]
Now I'm getting this when trying to auto-redeem keys:
> Traceback (most recent call last):
  File "/home/metafarion/Downloads/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 925, in <module>
    redeem_steam_keys(humble_session, steam_keys if try_already_revealed else unrevealed_keys)
                      ^^^^^^^^^^^^^^
NameError: name 'humble_session' is not defined

This is after saying Yes redeem un-revealed keys and Yes attempt to redeem already-revealed keys.

**Comment by FailSpy** [comment]
Updated to fix. Let me know if there's any other issues

**Comment by metafarion** [comment]
Yesss!  That did it!  I just redeemed like 500 keys this afternoon!
I have one more error for you though, so hang on...
