### ISSUE TITLE
Unable to paste into Password fields - Massive pain for those with actually secure passwords

### ISSUE THREAD

**Issue by Fevix** [FailSpy/humble-steam-key-redeemer#38]
This thing tells me that the email and password don't match, but I'm literally copypasting the password from my password manager the same way I do to log into the website. 

Could it just not support 2FA?

**Comment by Fevix** [comment]
Nevermind, it just doesn't support pasting into the password fields. I'm changing this to a feature request for those of us who use password managers and therefore our passwords look like "$4DQrMKPY7r9S%dexYMh" (freshly generated password, unused, don't worry I'm not that level of dumb)

**Comment by FailSpy** [comment]
I use a password manager as well, and quite happily copy paste into it.

Are you sure you're using the Paste command for your respective command prompt/terminal? There's not much I can do to make pasting work for your terminal, at best I can offer a separate feature to capture from your clipboard, which seems excessive.

Most terminals support CTRL+SHIFT+V or Middle-click. 
If you're on Windows 10+, you can enable CTRL SHIFT V on the Terminal's settings, or alternatively as a quick fix just right click and use Paste, or SHIFT+INSERT.

**Comment by FailSpy** [comment]
Closing as I've added a QOL feature in [53a266f](https://github.com/FailSpy/humble-steam-key-redeemer/commit/53a266fe981cf62ca6cd0379be87a38327d3b62d) to make sure this is more evident in the future by adding a password mask (using a shrunk down version of [pwinput](https://github.com/asweigart/pwinput)) to give the user feedback that they're entering characters.
